### ISSUE TITLE
[Bug but could be device specific] default calendar app does not stick when open an event

### ISSUE THREAD

**Issue by redhonker66** [andstatus/todoagenda#23]
Pressing + will open the default calendar app.  If it's not yet set, will prompt.  Once you choose default, it will stick.

However, opening on event from the widget will always prompt which calendar app to use, regardless whether you've checked default checkbox last time.

I only have this on my LG devices.  Not sure if this is device specific.

**Comment by yvolk** [comment]
1. First of all: 
Adding new event (""android.intent.action.INSERT"")  and
Viewing (or editing) existing event ("android.intent.action.VIEW")
are different actions from Android System's point of view. So no wonder that selecting default app (e.g. calendar app) for one action does not automatically sets the same app for another action.

2. This is Android system (i.e. a device's firmware), not our "ToDo Agenda widget" that asks a User for the default app, and that remembers (or not) that chosen default. ToDo Agenda only sends an "Intent" to the Android Systems, telling, what a User wants to do. And then Android Systems decides, what to do: it may search for existing default, search for apps that declared their ability to handle this "Intent"...

3. Clicks on different events naturally produce slightly different "VIEW Intents", because each Intent should contain ID of a particular event to be viewed. This could be potentially a cause of a difficulty to remember a default... 

Conclusion:
1. This problem is at least partially a deficiency (or a bug) of the device's firmware (or maybe of Android in general). I may be specific to Android version or to a device brand...
2. We need more info about different devices / Android versions in order figure out how to fix the problem. The solution may be "Update your device's firmware"...

**Comment by yvolk** [comment]
@redhonker66 I suspect that this bug/problem was fixed in ToDo Agenda v.4.0+
I changed a way "intents" to open Calendar apps are created...
Please test, it's available both in F-Droid and Google Play, see https://github.com/andstatus/todoagenda#readme

**Comment by redhonker66** [comment]
Hi,

I'm running 4.1.1.  The problem remains in LG device.  I got a Samsung and I can confirm it's not there.

Thanks
